### ISSUE TITLE
apk

### ISSUE THREAD

**Issue by migtorr** [anaisbetts/poolsuite-androidtv#1]
Hi, I know you are busy having a pina colada by the pool but can you build an apk and share it over here?

**Comment by anaisbetts** [comment]
https://github.com/anaisbetts/poolsuite-androidtv#why-dont-you-build-it-for-me

tbh, I also need to fix this, it's broken at the moment

**Edit:** uhhh jk, it works now 😅   Looks like whatever Poolsuite did to break the app, they changed it back
